controllers:
    resource: ../src/Controller/
    type: attribute

getGames:
    path: /api/games/get/{id}
    controller: App\Controller\GamesController::getGamesById

addGame:
    path: /api/games/add/{id}
    controller: App\Controller\GamesController::addGameById